FROM httpd:2.4.43

RUN apt-get update && apt-get install -y git

WORKDIR /usr/local/apache2

RUN git clone https://github.com/stephenp88/covid-19-dashboard.git

RUN cp ./covid-19-dashboard/dashboard/*.* ./htdocs/

EXPOSE 80
